### ISSUE TITLE
Convert existing JS class components to TSX function components throughout the demos

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-virtualized-extension#17]
Step 1 of upgrading the virtualized table components to v5
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/react-virtualized-extension/pull/19
- [ ] https://github.com/patternfly/react-virtualized-extension/pull/20
- [ ] https://github.com/patternfly/react-virtualized-extension/pull/21
- [ ] https://github.com/patternfly/react-virtualized-extension/pull/22
```
